# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 033b756e90c6a6fcd6fa2703cd63f366f123cf11af68bcb1150099fe10ef02058fcd9bf1ffbcb40aececb0761acd980a216d2b32798180e493a716e2f536e541

test:
  secret_key_base: 00947de45564ad0d1437d5315b151455231e3e7126372cb4c9f559f654bf3e4817a682265f51d81878e7535dc5d06572216abc9dd48bf792b6d818ef4f0f168c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
